// Stage E: AI polish via Cloud Agents + AST contract and in-process tsc gates.

import * as path from 'node:path';
import * as fs from 'node:fs';
import * as ts from 'typescript';
import {
  buildCloudPolishPrompt,
  chunkByApis,
  type CloudPolishTarget,
} from '../../src/polish/prompt.js';
import {
  ensureCloudIds,
  formatPolishSummary,
  parsePolishReply,
  runCloudTurn,
  summarizePolish,
  type CloudIdStore,
  type PolishSummary,
} from '../../src/polish/cloud.js';
import {
  harvestPolishedEntry,
  loadLedger,
  loadPolishedArtifact,
  saveLedger,
} from '../../src/ledger/index.js';
import { parseHeader } from '../../src/ledger/parse.js';
import { extractTypeDesign, validatePolishedSource } from '../../src/polish/validate.js';

// APIs per cloud turn. The whole batch comes back as one reply, so this bounds
// the response length — a truncated reply costs the entire batch.
const APIS_PER_BATCH = 6;

export interface PolishRequest {
  files: string[];
  stage1Sources?: Record<string, string>;
  workspaceRoot: string;
  cloud: { pat: string; store: CloudIdStore };
  signal?: AbortSignal;
  onProgress: (msg: string) => void;
  onLog: (msg: string) => void;
}

export interface PolishFileReport {
  name: string;
  file: string;
  status: 'polished' | 'reverted' | 'failed';
  /** Stage-1 source, kept so the panel can diff it against what is on disk. */
  stage1: string;
  summary?: PolishSummary;
}

export interface PolishResult {
  polished: number;
  reverted: number;
  report: PolishFileReport[];
}

function readApis(filePath: string): { httpMethod: string; url: string; docName: string }[] {
  const apis: { httpMethod: string; url: string; docName: string }[] = [];
  for (const line of fs.readFileSync(filePath, 'utf8').split('\n')) {
    const m = /^\/\/ ([A-Z]+) (\/\S*)\s*(.*)$/.exec(line);
    if (m) apis.push({ httpMethod: m[1]!, url: m[2]!, docName: m[3]!.trim() });
  }
  return apis.length > 0
    ? apis
    : [{ httpMethod: 'POST', url: '', docName: path.basename(filePath, '.ts') }];
}

// Diagnostics about unresolved imports are expected: the generated files import
// the host project's request client and pagination type, which are outside the
// checked file set. The gate is here to catch what the AI can break — duplicate
// identifiers and dangling references after a rename.
const IGNORED_DIAGNOSTICS = new Set([
  2307, // Cannot find module
  2792, // Cannot find module, consider moduleResolution
  2686, // refers to a UMD global
]);

function typeCheck(files: string[], outputDir: string): { ok: boolean; brokenFiles: Set<string> } {
  const compilerOptions: ts.CompilerOptions = {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    strict: true,
    noEmit: true,
    skipLibCheck: true,
    baseUrl: outputDir,
  };

  const program = ts.createProgram(files, compilerOptions);
  const diagnostics = ts
    .getPreEmitDiagnostics(program)
    .filter((d) => !IGNORED_DIAGNOSTICS.has(d.code));

  const brokenFiles = new Set<string>();
  for (const d of diagnostics) {
    if (d.file) brokenFiles.add(path.basename(d.file.fileName));
  }
  return { ok: diagnostics.length === 0, brokenFiles };
}

// Mark a polished file so readers know its names are AI-refined and pinned by
// the ledger, and so a later generate run does not clobber it.
function markStage2(file: string): void {
  const src = fs.readFileSync(file, 'utf8');
  if (src.includes('Stage-2')) return;
  const next = src.replace(
    /^\/\/ AUTO-GENERATED by openapi-qoder Stage-1\. Do not edit by hand\.$/m,
    '// AUTO-GENERATED by openapi-qoder (Stage-1 codegen + Stage-2 AI polish).\n' +
      '// Type contract validated; decisions are cached under .openapi-qoder/.',
  );
  if (next !== src) fs.writeFileSync(file, next);
}

// The model always replies with LF, but Stage-1 files may be CRLF on Windows.
// Match the original file's line endings so a rename does not churn every line.
function matchEol(next: string, original: string): string {
  return original.includes('\r\n') ? next.replace(/\r?\n/g, '\r\n') : next;
}

function stage1Of(target: CloudPolishTarget): string {
  return target.stage1Content ?? target.content;
}

export async function polishFiles(req: PolishRequest): Promise<PolishResult> {
  const outputDir = path.dirname(req.files[0]!);
  const ledgerPath = path.join(req.workspaceRoot, '.openapi-qoder', 'naming.lock.json');
  const ledger = loadLedger(ledgerPath);

  // Stage-1 content is kept in memory: it is both the rollback source and the
  // "before" side of the ledger diff.
  const targets: CloudPolishTarget[] = [];

  for (const file of req.files) {
    const content = fs.readFileSync(file, 'utf8');
    if (content.includes('Stage-2')) {
      req.onLog(`[skip] ${path.basename(file)} 已有 Stage-2 标记`);
      continue;
    }
    const name = path.basename(file);
    const stage1Content = req.stage1Sources?.[name] ?? content;
    const { docId } = parseHeader(stage1Content);
    const entry = ledger.apis[docId];
    const previous = entry ? loadPolishedArtifact(req.workspaceRoot, entry) : undefined;
    targets.push({
      file,
      name,
      content,
      stage1Content,
      apis: readApis(file),
      previousContent: previous ? extractTypeDesign(previous) : undefined,
    });
  }

  if (targets.length === 0) {
    req.onLog('[polish] 没有需要润色的文件');
    return { polished: 0, reverted: 0, report: [] };
  }

  if (req.signal?.aborted) throw new Error('已取消');

  const ids = await ensureCloudIds(req.cloud.pat, req.cloud.store, req.onLog);
  const batches = chunkByApis(targets, APIS_PER_BATCH);
  const apiCount = targets.reduce((sum, t) => sum + t.apis.length, 0);

  req.onProgress(`AI 润色 ${targets.length} 个文件 (${apiCount} 个接口, ${batches.length} 批)...`);

  const report: PolishFileReport[] = [];
  let reverted = 0;

  for (const [i, batch] of batches.entries()) {
    if (req.signal?.aborted) throw new Error('已取消');

    const label = `批次 ${i + 1}/${batches.length}`;
    req.onProgress(`${label}: ${batch.map((t) => t.name).join(', ')}`);

    let replies: Map<string, string>;
    try {
      const text = buildCloudPolishPrompt(batch);
      req.onLog(`[polish] ${label} prompt ${text.length} 字符`);
      const reply = await runCloudTurn({
        pat: req.cloud.pat,
        ids,
        text,
        signal: req.signal,
        log: req.onLog,
      });
      replies = parsePolishReply(reply, batch, req.onLog);
    } catch (err) {
      if (req.signal?.aborted) throw new Error('已取消');
      // Nothing was written yet, so Stage-1 already stands — just report and move
      // on, so one bad batch does not cost the whole run.
      req.onProgress(`${label} 失败，保留 Stage-1`);
      req.onLog(`[error] ${label}: ${(err as Error).message}`);
      for (const t of batch) {
        report.push({ name: t.name, file: t.file, status: 'failed', stage1: stage1Of(t) });
      }
      continue;
    }

    const written: string[] = [];
    for (const t of batch) {
      const next = replies.get(t.name);
      if (next === undefined) {
        req.onLog(`[warn] ${t.name} 未在回复中出现，保持 Stage-1`);
        report.push({ name: t.name, file: t.file, status: 'failed', stage1: stage1Of(t) });
        continue;
      }
      const withEol = matchEol(next, t.content);
      const validation = validatePolishedSource(stage1Of(t), withEol);
      if (!validation.ok) {
        reverted++;
        req.onProgress(`↺ 回滚 ${t.name} (接口契约变化)`);
        req.onLog(`[contract] ${t.name}: ${validation.errors.slice(0, 3).join('; ')}`);
        report.push({ name: t.name, file: t.file, status: 'reverted', stage1: stage1Of(t) });
        continue;
      }
      if (withEol !== t.content) fs.writeFileSync(t.file, withEol);
      written.push(t.name);
    }

    if (written.length === 0) continue;

    req.onLog(`[tsc] ${label} 检查编译...`);
    const allTs = fs
      .readdirSync(outputDir)
      .filter((f) => f.endsWith('.ts'))
      .map((f) => path.join(outputDir, f));
    const { brokenFiles } = typeCheck(allTs, outputDir);

    for (const t of batch) {
      if (!written.includes(t.name)) continue;
      if (brokenFiles.has(t.name)) {
        fs.writeFileSync(t.file, t.content);
        reverted++;
        req.onProgress(`↺ 回滚 ${t.name} (编译失败)`);
        req.onLog(`[tsc] 回滚 ${t.name}`);
        report.push({ name: t.name, file: t.file, status: 'reverted', stage1: stage1Of(t) });
      } else {
        markStage2(t.file);
        const summary = summarizePolish(t.content, fs.readFileSync(t.file, 'utf8'));
        req.onLog(formatPolishSummary(t.name, summary));
        report.push({ name: t.name, file: t.file, status: 'polished', stage1: stage1Of(t), summary });
      }
    }
  }

  const polishedFiles = report.filter((r) => r.status === 'polished');

  // Record validated decisions and a replayable artifact for future generations.
  if (polishedFiles.length > 0) {
    req.onProgress('记录润色结果到账本...');
    for (const entryFile of polishedFiles) {
      const after = fs.readFileSync(entryFile.file, 'utf8');
      const { docId } = parseHeader(entryFile.stage1);
      if (docId === '-') continue;
      if (ledger.apis[docId]?.source === 'manual') continue;

      const meta = /^\/\/ (\S+) (\S+)/m.exec(entryFile.stage1.split('\n')[1] ?? '');
      const entry = harvestPolishedEntry(req.workspaceRoot, entryFile.stage1, after, {
        httpMethod: meta?.[1] ?? 'POST',
        url: meta?.[2] ?? '',
      });
      if (entry) ledger.apis[docId] = { ...ledger.apis[docId], ...entry };
    }
    saveLedger(ledgerPath, ledger);
    req.onLog('[polish] 账本已更新');
  }

  return { polished: polishedFiles.length, reverted, report };
}
