// Stage-2 orchestration: run the Qoder agent, verify contract equivalence, then
// gate the result on `tsc`. Invalid output is restored from the input snapshot.

import { execFileSync } from 'node:child_process';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from 'node:fs';
import { basename, join } from 'node:path';
import {
  query,
  accessTokenFromEnv,
  qodercliAuth,
  DEFAULT_ACCESS_TOKEN_ENV_VAR,
} from '@qoder-ai/qoder-agent-sdk';
import { loadLedger, loadPolishedArtifact } from '../ledger/index.js';
import { parseHeader } from '../ledger/parse.js';
import { buildPolishPrompt, chunkByApis, type PolishTarget } from './prompt.js';
import { extractTypeDesign, validatePolishedSource } from './validate.js';

export interface PolishConfig {
  /** Directory holding Stage-1 output (also the tsc project root scope). */
  srcDir: string;
  /** Directory to write polished files into. */
  outDir: string;
  /** tsconfig used to validate the polished output. */
  tsconfig: string;
  /** Repo root, used as agent cwd and for running tsc. */
  root: string;
  /** Files per agent invocation. */
  batchSize?: number;
  maxTurns?: number;
}

function resolveAuth() {
  // Prefer an explicit PAT; fall back to local `qodercli login` state.
  return process.env[DEFAULT_ACCESS_TOKEN_ENV_VAR] ? accessTokenFromEnv() : qodercliAuth();
}

// Pull API metadata back out of the Stage-1 header comments so the agent gets
// naming context without re-fetching Torna. A merged folder file carries one
// `// METHOD /url  name` line per API, so collect them all — giving the agent
// only the first would make it name every type after that one API's domain.
function readApis(file: string): { httpMethod: string; url: string; docName: string }[] {
  const apis: { httpMethod: string; url: string; docName: string }[] = [];
  // Each API's comment sits above its own section, so scan the whole file. The
  // all-caps-method + /path shape does not match the other header comments.
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    const m = /^\/\/ ([A-Z]+) (\/\S*)\s*(.*)$/.exec(line);
    if (m) apis.push({ httpMethod: m[1]!, url: m[2]!, docName: m[3]!.trim() });
  }
  return apis.length > 0
    ? apis
    : [{ httpMethod: 'POST', url: '', docName: basename(file, '.ts') }];
}

function typeCheck(cfg: PolishConfig): { ok: boolean; output: string } {
  // Invoke the compiler entrypoint through node: the .bin/tsc shim is a shell
  // script and is not directly executable via execFile on Windows.
  const tscJs = join(cfg.root, 'node_modules', 'typescript', 'bin', 'tsc');
  try {
    execFileSync(process.execPath, [tscJs, '-p', cfg.tsconfig], {
      cwd: cfg.root,
      encoding: 'utf8',
      stdio: 'pipe',
    });
    return { ok: true, output: '' };
  } catch (err) {
    const e = err as { stdout?: string; stderr?: string; message?: string };
    return { ok: false, output: `${e.stdout ?? ''}${e.stderr ?? ''}` || (e.message ?? 'tsc failed') };
  }
}

function filesWithErrors(tscOutput: string): Set<string> {
  const names = new Set<string>();
  for (const line of tscOutput.split('\n')) {
    const m = /^(.*?\.ts)\(\d+,\d+\)/.exec(line.trim());
    if (m) names.add(basename(m[1]!));
  }
  return names;
}

async function runAgent(targets: PolishTarget[], cfg: PolishConfig): Promise<void> {
  const q = query({
    prompt: buildPolishPrompt(targets),
    options: {
      auth: resolveAuth(),
      cwd: cfg.root,
      permissionMode: 'acceptEdits',
      allowedTools: ['Read', 'Edit'],
      settingSources: [],
      maxTurns: cfg.maxTurns ?? 40,
    },
  });

  try {
    for await (const msg of q) {
      if (msg.type === 'result') {
        if (msg.subtype !== 'success') {
          // Run failures arrive as result messages, not thrown errors.
          throw new Error(`agent run failed: ${msg.subtype}`);
        }
      }
    }
  } finally {
    q.close();
  }
}

// Mark a polished file as having passed Stage-2 so readers know the names were
// AI-refined and are pinned by the ledger (not safe to hand-edit ad hoc).
function markStage2(file: string): void {
  const src = readFileSync(file, 'utf8');
  if (src.includes('Stage-2')) return;
  const next = src.replace(
    /^\/\/ AUTO-GENERATED by openapi-qoder Stage-1\. Do not edit by hand\.$/m,
    '// AUTO-GENERATED by openapi-qoder (Stage-1 codegen + Stage-2 AI polish).\n' +
      '// Type contract validated; decisions are cached under .openapi-qoder/.',
  );
  if (next !== src) writeFileSync(file, next);
}

export async function polish(cfg: PolishConfig): Promise<void> {
  mkdirSync(cfg.outDir, { recursive: true });

  // Seed the polish dir from Stage-1, but do NOT clobber files that already
  // carry a Stage-2 banner — that makes re-runs resumable after interruption.
  const names = readdirSync(cfg.srcDir).filter((f) => f.endsWith('.ts'));
  for (const n of names) {
    const dst = join(cfg.outDir, n);
    if (!existsSync(dst)) copyFileSync(join(cfg.srcDir, n), dst);
  }

  // common.ts and the request stub are infrastructure — never polished.
  const editable = names.filter((n) => n !== 'common.ts' && !n.startsWith('_'));

  // Snapshot each target's CURRENT content in memory. Rollback restores from
  // here, so it survives even if srcDir is deleted mid-run (a real hazard when
  // external tooling runs `git clean` on the untracked artifact tree).
  const snapshot = new Map<string, string>();
  const pending: PolishTarget[] = [];
  const ledger = loadLedger(join(cfg.root, '.openapi-qoder', 'naming.lock.json'));
  let alreadyDone = 0;
  for (const n of editable) {
    const file = join(cfg.outDir, n);
    const content = readFileSync(file, 'utf8');
    if (content.includes('Stage-2')) {
      alreadyDone++;
      continue; // resume: skip files polished in a previous run
    }
    const stage1Content = readFileSync(join(cfg.srcDir, n), 'utf8');
    const { docId } = parseHeader(stage1Content);
    const entry = ledger.apis[docId];
    const previous = entry ? loadPolishedArtifact(cfg.root, entry) : undefined;
    snapshot.set(n, content);
    pending.push({
      file,
      stage1Content,
      apis: readApis(file),
      previousContent: previous ? extractTypeDesign(previous) : undefined,
    });
  }

  const targets = pending;
  const batches = chunkByApis(targets, cfg.batchSize ?? 6);
  console.log(
    `Polishing ${targets.length} file(s) in ${batches.length} batch(es)` +
      (alreadyDone ? ` (${alreadyDone} already done, skipped)` : '') +
      '...',
  );

  for (const [i, batch] of batches.entries()) {
    console.log(`\n[batch ${i + 1}/${batches.length}] ${batch.length} file(s)`);
    try {
      await runAgent(batch, cfg);
    } catch (err) {
      console.error(`  agent error: ${(err as Error).message}`);
    }

    const rejected = new Set<string>();
    for (const t of batch) {
      const name = basename(t.file);
      const before = snapshot.get(name)!;
      const after = readFileSync(t.file, 'utf8');
      const validation = validatePolishedSource(t.stage1Content ?? before, after);
      if (!validation.ok) {
        writeFileSync(t.file, before);
        rejected.add(name);
        console.warn(`  ↺ reverted ${name} (contract changed)`);
        console.warn(`    ${validation.errors.slice(0, 3).join('\n    ')}`);
      }
    }

    // Validate after each batch and roll back only the files that broke.
    const check = typeCheck(cfg);
    if (!check.ok) {
      const broken = filesWithErrors(check.output);
      let restored = 0;
      for (const t of batch) {
        const name = basename(t.file);
        if (rejected.has(name)) continue;
        if (broken.has(name)) {
          writeFileSync(t.file, snapshot.get(name)!); // in-memory rollback
          restored++;
          console.warn(`  ↺ reverted ${name} (did not compile)`);
        } else {
          markStage2(t.file);
        }
      }
      if (restored === 0 && rejected.size === 0) {
        console.warn(`  tsc failed but no batch file matched:\n${check.output.slice(0, 800)}`);
      }
    } else {
      for (const t of batch) {
        if (!rejected.has(basename(t.file))) markStage2(t.file);
      }
      console.log('  ✓ batch contract and compilation checks passed');
    }
  }

  const final = typeCheck(cfg);
  console.log(final.ok ? '\nAll polished files compile.' : `\nFinal tsc still failing:\n${final.output.slice(0, 1200)}`);
}

// Report what changed relative to Stage-1, for human review.
export function summarize(srcDir: string, outDir: string): void {
  const names = readdirSync(outDir).filter(
    (f) => f.endsWith('.ts') && f !== 'common.ts' && !f.startsWith('_'),
  );
  let changed = 0;
  let unknownFixed = 0;
  for (const n of names) {
    const beforePath = join(srcDir, n);
    if (!existsSync(beforePath)) continue;
    const before = readFileSync(beforePath, 'utf8');
    const after = readFileSync(join(outDir, n), 'utf8');
    if (before !== after) changed++;
    const cnt = (s: string) => (s.match(/unknown\[\]/g) ?? []).length;
    unknownFixed += Math.max(0, cnt(before) - cnt(after));
  }
  console.log(`\nChanged ${changed}/${names.length} file(s); resolved ${unknownFixed} unknown[] field(s).`);
}
