// AUTO-GENERATED by openapi-qoder (Stage-1 codegen + Stage-2 AI polish).
// Names are pinned in .openapi-qoder/naming.lock.json — edit there, not here.
// 目录 信审订单产品控制器  (6 API(s))
// docId: a85ywLg8  shape: 0f1bfb27f095
// apiShapes: YX0l9jGX=65ba7e7d5c11 58pnGWWz=33fa7c3c04e5 V2JVA4Y2=17ea63e27995 e24QpmL8=538a2a992d4e VXE7ApE2=548fe5c4234c 42GQ6JXW=3dfa34d16f2c
import request from '@/utils/request';


// GET /api/v1/credit/batteryProduct/bundle/hed/list  查询产品套餐列表 骐骥HED、十方

/** 查询产品套餐列表 骐骥HED、十方入参 */
export interface HedBatteryBundleListParam {
  planId?: string;
  batModel?: string;
}

/** 电池保证金档位 */
export interface DepositStepVO {
  lowerBound?: number;
  upperBound?: number;
  price?: number;
}

/** 订单产品套餐信息 */
export interface BundleVO {
  /** 更新时间 */
  updateTime?: string;
  /** 更新人 */
  updateUser?: string;
  /** 更新人id */
  updater?: string;
  /** 创建时间 */
  createTime?: string;
  /** 创建人 */
  createUser?: string;
  /** 创建人id */
  creator?: string;
  /** 删除标识 */
  deleted?: number;
  /** 删除时间 */
  deletedTime?: string;
  /** 环境标识 */
  env?: string;
  /** 主键ID */
  id?: number;
  /** 产品ID */
  productId?: number;
  /** 套餐名称 */
  name?: string;
  /** 套餐编码 */
  packageCode?: string;
  /** 产品方案编码 */
  productSolutionCode?: string;
  /** 产品方案 */
  productSolution?: string;
  /** 商品名称 */
  productName?: string;
  /** 商品id */
  skuId?: string;
  /** 获客类别 */
  acquireType?: string;
  /** 电池限额（套） */
  batteryLimit?: number;
  /** 结算维度 */
  settleDim?: string;
  /** 租期(月) */
  leaseTermMonths?: string;
  /** 租金支付频率(如:月付、季付、年付) */
  repaymentFrequency?: string;
  /** 月套餐额度(kWh) */
  unitMonthlyUpperLimit?: number;
  /** 单套标准月租金(元/月) */
  unitMonthlyRent?: number;
  /** 电池银行月租金底价(单位分) */
  monthLowestPrice?: number;
  /** 单套实际月租金 */
  actualRent?: number;
  /** 单套电池起租前减免电量(kWh) */
  unitPreLeaseDeduction?: number;
  /** 超额里程单价 */
  excessPrice?: number;
  /** 起租规则 */
  rentRule?: string;
  /** 单套日租金（元/日） */
  dailyRent?: number;
  /** 超额度电金额(元/度) */
  excessElectricityFee?: number;
  /** 结转方式 */
  carryoverType?: string;
  /** 客户买断原价 */
  buyoutPrice?: number;
  /** 电池回购单价（元/kwh） */
  unitBatteryPrice?: number;
  /** 单套电池框架单价（元） */
  unitFramePrice?: number;
  /** 单套采购/回购价(元) */
  unitPurchasePrice?: number;
  /** 单套电池保证金金额(元) */
  unitDepositAmount?: number;
  /** 记录产品带过来的单套电池保证金金额(元) */
  unitDepositAmountHis?: number;
  /** 保险保证金 */
  insuranceDeposit?: number;
  /** 保险承担赔付比例（%） */
  insuranceRatio?: number;
  /** 税率（%） */
  taxRate?: number;
  /** 租户ID */
  tenantId?: string;
  /** 租户名称 */
  tenantName?: string;
  /** 机构ID */
  orgId?: string;
  /** 机构名称 */
  orgName?: string;
  /** 租金计算方式（前端交互用） Y-固定 N-动态 */
  priceCalcMode?: string;
  /** 套餐数量 */
  bundleNum?: number;
  /** 电池保证金模式 */
  batDepositMode?: string;
  /** 电池保证金档位 */
  depositSteps?: DepositStepVO[];
  /** 结转范围 */
  carryForwardRange?: string;
  packageId?: number;
}

/** 查询产品套餐列表 骐骥HED、十方出参 */
export interface HedBatteryBundleListData {
  /** 更新时间 */
  updateTime?: string;
  /** 更新人 */
  updateUser?: string;
  /** 更新人id */
  updater?: string;
  /** 创建时间 */
  createTime?: string;
  /** 创建人 */
  createUser?: string;
  /** 创建人id */
  creator?: string;
  /** 删除标识 */
  deleted?: number;
  /** 删除时间 */
  deletedTime?: string;
  /** 环境标识 */
  env?: string;
  /** 主键ID */
  id?: number;
  /** 信审uuid */
  creditId?: number;
  /** 电池型号 */
  batteryType?: string;
  /** 电池型号名称 */
  batteryTypeName?: string;
  /** 申请电池数量(套) */
  batteryQuantity?: number;
  /** 物料编号 */
  materialNumber?: string;
  /** 车辆型号 */
  vehicleModel?: string;
  /** 电池度数 */
  batteryCapacity?: number;
  /** 获客类别 */
  acquireType?: string;
  /** 电池限额（套） */
  batteryLimit?: number;
  /** 租户ID */
  tenantId?: string;
  /** 租户名称 */
  tenantName?: string;
  /** 机构ID */
  orgId?: string;
  /** 机构名称 */
  orgName?: string;
  /** 风控批复电池数量（套） */
  approvalBatteryQuantity?: number;
  /** 起租规则 */
  rentRule?: string;
  /** 备注 */
  remark?: string;
  /** 批复单套电池保证金金额（元） */
  approvalUnitDepositAmount?: string;
  /** 可用 */
  availableBatteryCount?: number;
  /** 已用 */
  applyBatteryCount?: number;
  /** 在租 */
  applyingBatteryCount?: number;
  /** 退组 */
  quitBatteryCount?: number;
  /** 订单产品套餐信息 */
  bundleList?: BundleVO[];
  version?: number;
  /** 产品id */
  planId?: number;
  /** 失效日期 */
  expirationDate?: string;
}

/** 查询产品套餐列表 骐骥HED、十方 */
export const getHedBatteryBundleList = (params: HedBatteryBundleListParam) =>
  request.get<HedBatteryBundleListData, HedBatteryBundleListParam>('/api/v1/credit/batteryProduct/bundle/hed/list', { params });

// GET /api/v1/credit/batteryProduct/hed/list  查询电池产品列表 骐骥HED、十方

/** 查询电池产品列表 骐骥HED、十方入参 */
export interface HedBatteryProductListParam {
  /** 电池型号 */
  batModel?: string;
  /** 业务类型 */
  businessType?: string;
  /** 使用场景 */
  usageScenario?: string;
  /** 渠道商编号 */
  channelCode?: string;
  /** 获客类别 */
  customerSourceType?: string;
  /** 是否是试用车 */
  isTestCar?: string;
}

/** 查询电池产品列表 骐骥HED、十方出参列表项 */
export interface HedBatteryProductListItem {
  /** 产品id */
  planId?: string;
  /** 产品名称 */
  planName?: string;
}

/** 查询电池产品列表 骐骥HED、十方出参 */
export type HedBatteryProductListData = HedBatteryProductListItem[];

/** 查询电池产品列表 骐骥HED、十方 */
export const getHedBatteryProductList = (params: HedBatteryProductListParam) =>
  request.get<HedBatteryProductListData, HedBatteryProductListParam>('/api/v1/credit/batteryProduct/hed/list', { params });

// GET /api/v1/credit/batteryProduct/list  查询电池产品列表 电服

/** 查询电池产品列表 电服入参 */
export interface ElecServiceBatteryProductListParam {
  /** 业务类型 */
  businessType?: string;
  /** 渠道编码 */
  channelCode?: string;
  /** 电池型号 */
  batModel?: string;
  /** 是否是试用车 */
  isTestCar?: string;
  /** 使用场景 */
  usageScenario?: string;
  /** 是否是运营 */
  isOperation?: string;
}

/** 车辆型号 */
export interface ElecServiceBatteryProductCarModelVO {
  code?: string;
  name?: string;
}

/** 查询电池产品列表 电服出参列表项 */
export interface ElecServiceBatteryProductListItem {
  /** 主键ID */
  id?: number;
  /** 套餐ID */
  bundleId?: number;
  /** 信审uuid */
  creditId?: number;
  /** 电池型号 */
  batteryType?: string;
  /** 电池型号名称 */
  batteryTypeName?: string;
  /** 申请电池数量(套) */
  batteryQuantity?: number;
  /** 物料编号 */
  materialNumber?: string;
  /** 车辆型号 */
  vehicleModel?: string;
  /** 电池度数 */
  batteryCapacity?: number;
  /** 获客类别 */
  acquireType?: string;
  /** 电池限额（套） */
  batteryLimit?: number;
  /** 租户ID */
  tenantId?: string;
  /** 租户名称 */
  tenantName?: string;
  /** 机构ID */
  orgId?: string;
  /** 机构名称 */
  orgName?: string;
  /** 风控批复电池数量（套） */
  approvalBatteryQuantity?: number;
  /** 备注 */
  remark?: string;
  /** 批复单套电池保证金金额（元） */
  approvalUnitDepositAmount?: string;
  /** 套餐名称 */
  name?: string;
  /** 套餐编码 */
  packageCode?: string;
  /** 产品方案编码 */
  productSolutionCode?: string;
  /** 产品方案 */
  productSolution?: string;
  /** 商品名称 */
  productName?: string;
  /** 商品id */
  skuId?: string;
  /** 结算维度 */
  settleDim?: string;
  /** 租期(月) */
  leaseTermMonths?: string;
  /** 租金支付频率(如:月付、季付、年付) */
  repaymentFrequency?: string;
  /** 月套餐额度(kWh) */
  unitMonthlyUpperLimit?: number;
  /** 单套标准月租金(元/月) */
  unitMonthlyRent?: number;
  /** 单套实际月租金 */
  actualRent?: number;
  /** 单套电池起租前减免电量(kWh) */
  unitPreLeaseDeduction?: number;
  /** 超额里程单价 */
  excessPrice?: number;
  /** 起租规则 */
  rentRule?: string;
  /** 单套日租金（元/日） */
  dailyRent?: number;
  /** 超额度电金额(元/度) */
  excessElectricityFee?: number;
  /** 结转方式 */
  carryoverType?: string;
  /** 结转范围 */
  carryForwardRange?: string;
  /** 客户买断原价 */
  buyoutPrice?: number;
  /** 电池回购单价（元/kwh） */
  unitBatteryPrice?: number;
  /** 单套电池框架单价（元） */
  unitFramePrice?: number;
  /** 单套采购/回购价(元) */
  unitPurchasePrice?: number;
  /** 单套电池保证金金额(元) */
  unitDepositAmount?: number;
  /** 保险保证金 */
  insuranceDeposit?: number;
  /** 保险承担赔付比例（%） */
  insuranceRatio?: number;
  /** 税率（%） */
  taxRate?: number;
  /** 车辆型号 */
  carModelDTOList?: ElecServiceBatteryProductCarModelVO[];
  /** 租金计算方式（前端交互用） Y-固定 N-动态 */
  priceCalcMode?: string;
  /** 套餐数量 */
  bundleNum?: number;
}

/** 查询电池产品列表 电服出参 */
export type ElecServiceBatteryProductListData = ElecServiceBatteryProductListItem[];

/** 查询电池产品列表 电服 */
export const getElecServiceBatteryProductList = (params: ElecServiceBatteryProductListParam) =>
  request.get<ElecServiceBatteryProductListData, ElecServiceBatteryProductListParam>('/api/v1/credit/batteryProduct/list', { params });

// GET /api/v1/credit/historyCoopInfo  查询历史合作信息

/** 查询历史合作信息入参 */
export interface CreditHistoryCoopInfoParam {
  creditCode: string;
}

/** 查询历史合作信息出参 */
export interface CreditHistoryCoopInfoData {
  /** 历史批复总套数 此客戶历史所有信审完成批复的套数 */
  approvedCount?: number;
  /** 历史起租总套数 */
  leasedCount?: number;
  /** 未起租套数（可用） */
  availableCount?: number;
  /** 在途申请套数 */
  applyingCount?: number;
  /** 风险敞口 */
  riskExposure?: number;
}

/** 查询历史合作信息 */
export const getCreditHistoryCoopInfo = (params: CreditHistoryCoopInfoParam) =>
  request.get<CreditHistoryCoopInfoData, CreditHistoryCoopInfoParam>('/api/v1/credit/historyCoopInfo', { params });

// GET /api/v1/credit/historyCoopInfoByCreditId  getHistoryCoopInfoByCreditId

/** 根据信审ID查询历史合作信息入参 */
export interface CreditHistoryCoopInfoByCreditIdParam {
  creditId: number;
}

/** 根据信审ID查询历史合作信息出参 */
export interface CreditHistoryCoopInfoByCreditIdData {
  /** 历史批复总套数 此客戶历史所有信审完成批复的套数 */
  approvedCount?: number;
  /** 历史起租总套数 */
  leasedCount?: number;
  /** 未起租套数（可用） */
  availableCount?: number;
  /** 在途申请套数 */
  applyingCount?: number;
  /** 风险敞口 */
  riskExposure?: number;
}

/** 根据信审ID查询历史合作信息 */
export const getCreditHistoryCoopInfoByCreditId = (params: CreditHistoryCoopInfoByCreditIdParam) =>
  request.get<CreditHistoryCoopInfoByCreditIdData, CreditHistoryCoopInfoByCreditIdParam>('/api/v1/credit/historyCoopInfoByCreditId', { params });

// GET /api/v1/credit/orderProduct/list  根据信审ID查询订单产品列表

/** 根据信审ID查询订单产品列表入参 */
export interface CreditOrderProductListParam {
  creditId: number;
}

/** 根据信审ID查询订单产品列表出参列表项 */
export interface CreditOrderProductListItem {
  /** 更新时间 */
  updateTime?: string;
  /** 更新人 */
  updateUser?: string;
  /** 更新人id */
  updater?: string;
  /** 创建时间 */
  createTime?: string;
  /** 创建人 */
  createUser?: string;
  /** 创建人id */
  creator?: string;
  /** 删除标识 */
  deleted?: number;
  /** 删除时间 */
  deletedTime?: string;
  /** 环境标识 */
  env?: string;
  /** 主键ID */
  id?: number;
  /** 信审uuid */
  creditId?: number;
  /** 电池型号 */
  batteryType?: string;
  /** 电池型号名称 */
  batteryTypeName?: string;
  /** 申请电池数量(套) */
  batteryQuantity?: number;
  /** 物料编号 */
  materialNumber?: string;
  /** 车辆型号 */
  vehicleModel?: string;
  /** 电池度数 */
  batteryCapacity?: number;
  /** 获客类别 */
  acquireType?: string;
  /** 电池限额（套） */
  batteryLimit?: number;
  /** 租户ID */
  tenantId?: string;
  /** 租户名称 */
  tenantName?: string;
  /** 机构ID */
  orgId?: string;
  /** 机构名称 */
  orgName?: string;
  /** 风控批复电池数量（套） */
  approvalBatteryQuantity?: number;
  /** 起租规则 */
  rentRule?: string;
  /** 备注 */
  remark?: string;
  /** 批复单套电池保证金金额（元） */
  approvalUnitDepositAmount?: string;
  /** 可用 */
  availableBatteryCount?: number;
  /** 已用 */
  applyBatteryCount?: number;
  /** 在租 */
  applyingBatteryCount?: number;
  /** 退组 */
  quitBatteryCount?: number;
  /** 订单产品套餐信息 */
  bundleList?: BundleVO[];
  version?: number;
  /** 产品id */
  planId?: number;
  /** 失效日期 */
  expirationDate?: string;
}

/** 根据信审ID查询订单产品列表出参 */
export type CreditOrderProductListData = CreditOrderProductListItem[];

/** 根据信审ID查询订单产品列表 */
export const getCreditOrderProductList = (params: CreditOrderProductListParam) =>
  request.get<CreditOrderProductListData, CreditOrderProductListParam>('/api/v1/credit/orderProduct/list', { params });
