// Ledger round-trip test (hermetic, no AI, no shared state).
//
// Verifies the guarantee that makes re-runs safe:
//   apply(stage1, entry)            -> polished
//   harvest(stage1, polished)       -> entry'   (must recover the decisions)
//   apply(stage1, entry')           -> polished (byte-identical)
//
// The seeded entry mirrors what the real Stage-2 agent produced for mock 1.

import { readFileSync } from 'node:fs';
import { applyEntry, harvestEntry, type ApiLedgerEntry } from './ledger/index.js';
import { parseFile, parseHeader } from './ledger/parse.js';
import { artifactDir } from './paths.js';

let failures = 0;

function check(label: string, ok: boolean, detail = ''): void {
  console.log(`  ${ok ? 'PASS' : 'FAIL'}  ${label}${detail ? `  ${detail}` : ''}`);
  if (!ok) failures++;
}

const cases: {
  file: string;
  fn: string;
  entry: Omit<ApiLedgerEntry, 'url' | 'httpMethod' | 'shape' | 'kind' | 'fns'>;
}[] = [
  {
    file: '1.ts',
    fn: 'getHostingVehiclePage',
    entry: {
      types: {
        HostingVehiclePageParam: 'HostingVehicleQueryParam',
        HostingVehiclePageItem: 'HostingVehicleVO',
        HostingVehiclePageData: 'HostingVehiclePageResult',
      },
      fieldTypes: {
        'HostingVehiclePageParam.assetOwnerCodes': 'string[]',
        'HostingVehiclePageParam.operatorCodes': 'string[]',
        'HostingVehiclePageParam.operatorNames': 'string[]',
        'HostingVehiclePageParam.createDate': 'string[]',
      },
      source: 'ai',
    },
  },
  {
    file: '5.ts',
    fn: 'getBillPage',
    entry: {
      types: { PcvQueryBillPageParam: 'BillQueryParam', PcvQueryBillPageItem: 'BillVO' },
      fieldTypes: { 'PcvQueryBillPageParam.bizTypeList': 'BizType[]' },
      source: 'ai',
    },
  },
];

for (const c of cases) {
  const stage1 = readFileSync(artifactDir(c.file), 'utf8');
  const { docId, shape } = parseHeader(stage1);
  const mechanicalFn = parseFile(stage1).fnNames[0]!;
  console.log(`\n${c.file}  docId=${docId} shape=${shape}`);

  const seeded: ApiLedgerEntry = {
    url: '',
    httpMethod: 'POST',
    kind: 'api',
    shape,
    fns: { [docId]: { mechanical: mechanicalFn, semantic: c.fn, locked: true } },
    ...c.entry,
  };

  // 1) apply
  const polished = applyEntry(stage1, seeded);
  check(
    'apply renamed types',
    Object.values(seeded.types).every((t) => polished.includes(t)),
  );
  check('apply renamed fn', polished.includes(`export const ${c.fn} =`));
  check(
    'apply resolved unknown[]',
    (polished.match(/unknown\[\]/g) ?? []).length <
      (stage1.match(/unknown\[\]/g) ?? []).length ||
      Object.keys(seeded.fieldTypes).length === 0,
  );
  check('apply left no mechanical names behind', !Object.keys(seeded.types).some((m) => polished.includes(m)));

  // 2) harvest back
  const recovered = harvestEntry(stage1, polished, { url: '', httpMethod: 'POST' });
  if (!recovered) {
    check('harvest returned an entry', false);
    continue;
  }
  check(
    'harvest recovered type map',
    JSON.stringify(recovered.types) === JSON.stringify(seeded.types),
    `${Object.keys(recovered.types).length} type(s)`,
  );
  check(
    'harvest recovered field types',
    JSON.stringify(recovered.fieldTypes) === JSON.stringify(seeded.fieldTypes),
    `${Object.keys(recovered.fieldTypes).length} field(s)`,
  );
  check(
    'harvest recovered fn',
    recovered.fns[docId]?.semantic === c.fn,
    recovered.fns[docId]?.semantic ?? '(none)',
  );
  check('harvest tagged kind', recovered.kind === 'api', recovered.kind);

  // 3) re-apply must be byte-identical => stable across runs
  const again = applyEntry(stage1, recovered);
  check('re-apply is byte-identical', again === polished);
}

// Structural-violation guard: if Stage-2 renamed a property key, harvest must
// refuse rather than record a corrupt mapping.
const stage1 = readFileSync(artifactDir('4.ts'), 'utf8');
const tampered = stage1.replace(/^(\s{2})vin(\??:)/m, '$1vinCode$2');
console.log('\nguard: property renamed by Stage-2');
check('harvest refuses corrupt pair', harvestEntry(stage1, tampered, { url: '', httpMethod: 'POST' }) === null);

// Merged folder files contain twin APIs, so `XParam` and `X2Param` coexist and a
// rename's target is routinely another rename's source. A sequential replace
// would collapse both onto one name.
const twins = `// AUTO-GENERATED by openapi-qoder Stage-1. Do not edit by hand.
// POST /a  d
// docId: FOLDER01  shape: aaa
// apiShapes: DOC1=h1 DOC2=h2
export interface PcvQueryBillPageParam {
  a?: string;
}
export interface PcvQueryBillPage2Param {
  b?: string;
}
export const pcvQueryBillPage = (data: PcvQueryBillPageParam) => request.post('/a', data);
export const pcvQueryBillPage2 = (data: PcvQueryBillPage2Param) => request.post('/b', data);
`;
console.log('\nguard: chained rename in a merged folder file');
{
  const entry: ApiLedgerEntry = {
    url: '',
    httpMethod: 'POST',
    kind: 'folder',
    shape: 'aaa',
    types: { PcvQueryBillPage2Param: 'PcvQueryBillPageParam', PcvQueryBillPageParam: 'BillQueryParamB' },
    fns: {
      DOC1: { mechanical: 'pcvQueryBillPage', semantic: 'queryBillPageB', locked: true },
      DOC2: { mechanical: 'pcvQueryBillPage2', semantic: 'queryBillPageM', locked: true },
    },
    fieldTypes: {},
    source: 'ai',
  };
  const out = applyEntry(twins, entry);
  check('both interfaces survive', /interface BillQueryParamB \{/.test(out) && /interface PcvQueryBillPageParam \{/.test(out));
  check(
    'no name collapsed onto another',
    (out.match(/export interface (\w+)/g) ?? []).length === 2 &&
      new Set(out.match(/export interface (\w+)/g)).size === 2,
  );
  check('each fn kept its own new name', out.includes('export const queryBillPageB =') && out.includes('export const queryBillPageM ='));
  check(
    'fn args follow their own interface',
    out.includes('queryBillPageB = (data: BillQueryParamB)') &&
      out.includes('queryBillPageM = (data: PcvQueryBillPageParam)'),
  );
}

console.log('\nguard: recorded fn no longer present');
{
  const entry: ApiLedgerEntry = {
    url: '',
    httpMethod: 'POST',
    kind: 'folder',
    shape: 'aaa',
    types: {},
    // Suffix shifted / API removed: this mechanical name is gone from the file.
    fns: { DOC9: { mechanical: 'pcvQueryBillPage9', semantic: 'shouldNotAppear', locked: true } },
    fieldTypes: {},
    source: 'ai',
  };
  check('stale fn rename is skipped', !applyEntry(twins, entry).includes('shouldNotAppear'));
}

console.log('\nguard: Stage-2 renamed two declarations to the same name');
{
  const collided = twins
    .replace('export interface PcvQueryBillPageParam {', 'export interface BillQueryParam {')
    .replace('export interface PcvQueryBillPage2Param {', 'export interface BillQueryParam {');
  check(
    'harvest refuses colliding targets',
    harvestEntry(twins, collided, { url: '', httpMethod: 'POST' }) === null,
  );
}

console.log(failures === 0 ? '\nAll ledger round-trip checks passed.' : `\n${failures} check(s) failed.`);
process.exitCode = failures === 0 ? 0 : 1;
