fetch("https://doc-dev.qijiswap.com/doc/view/dataByProject?projectId=57zL7ZXQ", {
    "headers": {
      "accept": "application/json, text/plain, */*",
      "accept-language": "zh-CN,zh;q=0.9",
      "cache-control": "no-cache",
      "pragma": "no-cache",
      "priority": "u=1, i",
      "sec-ch-ua": "\"Not=A?Brand\";v=\"99\", \"Google Chrome\";v=\"151\", \"Chromium\";v=\"151\"",
      "sec-ch-ua-mobile": "?0",
      "sec-ch-ua-platform": "\"Windows\"",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-origin",
      "token": "dJzAyzpZ:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3IiwiZXhwIjoxODE2MTM4ODU5LCJpYXQiOjE3ODQ2MDI4NTl9.DZoRPO0g28jfUzJepAXUdyPwMwtBoH2ncA8Uh5U4u-c",
      "Referer": "https://doc-dev.qijiswap.com/"
    },
    "body": null,
    "method": "GET"
  });


  /**
   * {
    "code": "0",
    "data": [
        {
            "apiCount": 96,
            "deprecated": "",
            "docId": null,
            "docType": null,
            "httpMethod": "",
            "id": "1537056406388080640",
            "label": "battery-investor-service",
            "origin": "",
            "parentId": "",
            "type": 1,
            "url": "",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "qXB64pWX",
            "docType": 0,
            "httpMethod": "GET",
            "id": "qXB64pWX",
            "label": "check",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "86e15f50f37251b0155b9e621a7438d5",
            "type": 3,
            "url": "/health/status",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "bXKWmrQX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "bXKWmrQX",
            "label": "查询租户全量权限配置树（2M专用）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "ef776f94967632929c7794611a2758bb",
            "type": 3,
            "url": "/2m/v1.0/bims/permission/tree",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "d2qR19v8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "d2qR19v8",
            "label": "运营车辆分页列表",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "1370edc4f1e37a5850a842605eea13a6",
            "type": 3,
            "url": "/2b/v1.0/operationVehicle/page",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "nzDyBg12",
            "docType": 0,
            "httpMethod": "POST",
            "id": "nzDyBg12",
            "label": "托管运营车辆分页列表",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "16aa0ca91781318f09ca578a7e38d875",
            "type": 3,
            "url": "/2m/v1.0/hostingVehicle/page",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "P81KOMmz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "P81KOMmz",
            "label": "2m模版下载",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "6a38115bfa7cfdd45026141a42c4649b",
            "type": 3,
            "url": "/2m/downloadExcelTemplate",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "E8rddqmz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "E8rddqmz",
            "label": "根据车牌号查询车辆VIN",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "04506d2e7bc4f8509fabde75ac7ee475",
            "type": 3,
            "url": "/inner/api/vehicle/queryByVehiclePlate",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "P81KKMwz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "P81KKMwz",
            "label": "获取在管电池清单分页列表",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "16d4f9354f75ab0a19131624e0739750",
            "type": 3,
            "url": "/2b/v1.0/pt/hostingBattery/list",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "Wz3jjoaX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "Wz3jjoaX",
            "label": "获取在库电池清单历史分页列表",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7a3f4f1c2e9fc25004e5439a8401cff9",
            "type": 3,
            "url": "/2b/v1.0/pt/hostingBatteryHistory/list",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "JzA33e48",
            "docType": 0,
            "httpMethod": "POST",
            "id": "JzA33e48",
            "label": "获取车辆轨迹列表（在地图上显示车辆运行轨迹）\r\n返回格式：[{\"name\":\"北京 -> 乌鲁木齐\",\"path\":[[经度，纬度],[经度，纬度],...]}]",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "9609dbb5e12bc80039bcdb81d08df968",
            "type": 3,
            "url": "/2b/v1.0/vehicleTrack/trackList",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "qXBZZQNX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "qXBZZQNX",
            "label": "获取出库历史数据列表（下载中心回调）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "66436718f202af900d43aae3b49e6798",
            "type": 3,
            "url": "/inner/api/batteryHistory/queryOutboundHistoryList",
            "version": ""
        },
        {
            "apiCount": 18,
            "deprecated": "",
            "docId": "PzmeeDlz",
            "docType": 0,
            "httpMethod": "",
            "id": "7f298dced62f86c0f2469c2a8e273d8f",
            "label": "资产运营监控",
            "origin": "",
            "parentId": "1537056406388080640",
            "type": 2,
            "url": "",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "N2eJJqx8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "N2eJJqx8",
            "label": "历史充电记录",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/2b/v1/pt/assetOperation/getChargeHistoryPage",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "BXgRRNL8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "BXgRRNL8",
            "label": "历史充电记录导出查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/inner/api/assetOperation/queryExportChargeHistory",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "NzvQQJqX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "NzvQQJqX",
            "label": "查询电池真实SOC",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "175d748563cde6fd8e36ceeb813d27b2",
            "type": 3,
            "url": "/open/api/getActualSocPage",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "YX0wwQG8",
            "docType": 0,
            "httpMethod": "GET",
            "id": "YX0wwQG8",
            "label": "检查是否值租户/持有方权限",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "026d537c99c22307070824ea569f3034",
            "type": 3,
            "url": "/2b/v1.0/auth/loginInfo",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "wXPwwbY8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "wXPwwbY8",
            "label": "车辆行驶明细导出查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "de5221eb512fa37fc2d414735bb9fcbb",
            "type": 3,
            "url": "/inner/api/vehicleOperation/queryExportVehicleDrive",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "wXnkpDEz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "wXnkpDEz",
            "label": "电池月初月末电量分页查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "01ec51156fe07f6f6049afbde480f911",
            "type": 3,
            "url": "/2b/v1/pt/settlement/monthStartEndPageQuery",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "B2lGJxgz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "B2lGJxgz",
            "label": "电池月初月末电量分页查询（下载中心回调）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "c1c1c6494242770d3df29e9dcae3b400",
            "type": 3,
            "url": "/inner/api/settlement/queryMonthStartEndList",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "42G5barX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "42G5barX",
            "label": "车辆行驶明细",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "de5221eb512fa37fc2d414735bb9fcbb",
            "type": 3,
            "url": "/2b/v1/pt/vehicleOperation/getVehicleDrivePage",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "B2lGlDrz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "B2lGlDrz",
            "label": "电池月初月末电量分页查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "01ec51156fe07f6f6049afbde480f911",
            "type": 3,
            "url": "/open/api/v1/pt/settlement/monthStartEndPageQuery",
            "version": ""
        },
        {
            "apiCount": 2,
            "deprecated": "",
            "docId": "d2qR1nJ8",
            "docType": 0,
            "httpMethod": "",
            "id": "7a3f4f1c2e9fc25004e5439a8401cff9",
            "label": "在库电池清单历史 Controller",
            "origin": "",
            "parentId": "1537056406388080640",
            "type": 2,
            "url": "",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "ez7oxnwz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "ez7oxnwz",
            "label": "查询运营商全量权限配置树（2B专用）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "ef776f94967632929c7794611a2758bb",
            "type": 3,
            "url": "/2b/v1.0/bims/permission/tree",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "VXEkPEv2",
            "docType": 0,
            "httpMethod": "POST",
            "id": "VXEkPEv2",
            "label": "车辆运营商分配-数据校验",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "1370edc4f1e37a5850a842605eea13a6",
            "type": 3,
            "url": "/2b/v1.0/operationVehicle/validateAssignCarrier",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "K8MoRd0z",
            "docType": 0,
            "httpMethod": "POST",
            "id": "K8MoRd0z",
            "label": "新增车辆",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "16aa0ca91781318f09ca578a7e38d875",
            "type": 3,
            "url": "/2m/v1.0/hostingVehicle/importCreate",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "58ppNlD8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "58ppNlD8",
            "label": "2b模版下载",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "6a38115bfa7cfdd45026141a42c4649b",
            "type": 3,
            "url": "/2b/downloadExcelTemplate",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "42G55GEX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "42G55GEX",
            "label": "导出（下载中心）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "16d4f9354f75ab0a19131624e0739750",
            "type": 3,
            "url": "/2b/v1.0/pt/hostingBattery/export",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "VzNRR0qz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "VzNRR0qz",
            "label": "导出到下载中心",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7a3f4f1c2e9fc25004e5439a8401cff9",
            "type": 3,
            "url": "/2b/v1.0/pt/hostingBatteryHistory/export",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "a26ooyq8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "a26ooyq8",
            "label": "获取运营车辆列表(下载中心回调)",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "04506d2e7bc4f8509fabde75ac7ee475",
            "type": 3,
            "url": "/inner/api/vehicle/queryVehicleList",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "d2q00BNz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "d2q00BNz",
            "label": "获取车辆信息",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "9609dbb5e12bc80039bcdb81d08df968",
            "type": 3,
            "url": "/2b/v1.0/vehicleTrack/vehicleInfo",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "wXnkkMmz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "wXnkkMmz",
            "label": "历史充电记录导出",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/2b/v1/pt/assetOperation/exportChargeHistory",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "B2lGGRVz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "B2lGGRVz",
            "label": "历史放电记录导出查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/inner/api/assetOperation/queryExportDischargeHistory",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "a26ooQl8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "a26ooQl8",
            "label": "电池位置查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "175d748563cde6fd8e36ceeb813d27b2",
            "type": 3,
            "url": "/open/api/getBatteryLocationPage",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "7zLOO1oX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "7zLOO1oX",
            "label": "车辆充电明细导出查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "de5221eb512fa37fc2d414735bb9fcbb",
            "type": 3,
            "url": "/inner/api/vehicleOperation/queryExportVehicleCharge",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "d8xV96yz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "d8xV96yz",
            "label": "电池月初月末电量分页查询导出（下载中心）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "01ec51156fe07f6f6049afbde480f911",
            "type": 3,
            "url": "/2b/v1/pt/settlement/exportMonthStartEndPageQuery",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "aXYwOjj2",
            "docType": 0,
            "httpMethod": "POST",
            "id": "aXYwOjj2",
            "label": "车辆月使用情况分页查询（下载中心回调）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "c1c1c6494242770d3df29e9dcae3b400",
            "type": 3,
            "url": "/inner/api/settlement/queryVehicleMonthlyUseList",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "m8wo9D78",
            "docType": 0,
            "httpMethod": "POST",
            "id": "m8wo9D78",
            "label": "车辆充电明细",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "de5221eb512fa37fc2d414735bb9fcbb",
            "type": 3,
            "url": "/2b/v1/pt/vehicleOperation/getVehicleChargePage",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "aXYweBY2",
            "docType": 0,
            "httpMethod": "POST",
            "id": "aXYweBY2",
            "label": "车辆月使用情况分页查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "01ec51156fe07f6f6049afbde480f911",
            "type": 3,
            "url": "/open/api/v1/pt/settlement/vehicleMonthlyUseQuery",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "NzvZmowz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "NzvZmowz",
            "label": "更新租户/运营商权限（2M专用）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "ef776f94967632929c7794611a2758bb",
            "type": 3,
            "url": "/2m/v1.0/bims/permission/update",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "r2jla0kX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "r2jla0kX",
            "label": "车辆运营商分配-数据提交",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "1370edc4f1e37a5850a842605eea13a6",
            "type": 3,
            "url": "/2b/v1.0/operationVehicle/submitAssignCarrier",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "W2onBYaz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "W2onBYaz",
            "label": "解除车辆\\批量解除车辆",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "16aa0ca91781318f09ca578a7e38d875",
            "type": 3,
            "url": "/2m/v1.0/hostingVehicle/importUnbound",
            "version": ""
        },
        {
            "apiCount": 3,
            "deprecated": "",
            "docId": "58ppv9L8",
            "docType": 0,
            "httpMethod": "",
            "id": "9609dbb5e12bc80039bcdb81d08df968",
            "label": "车辆位置追踪 Controller",
            "origin": "",
            "parentId": "1537056406388080640",
            "type": 2,
            "url": "",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "m8wooMj8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "m8wooMj8",
            "label": "分配运营商",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "16d4f9354f75ab0a19131624e0739750",
            "type": 3,
            "url": "/2b/v1.0/pt/hostingBattery/assignOperator",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "BXgRRM78",
            "docType": 0,
            "httpMethod": "POST",
            "id": "BXgRRM78",
            "label": "获取解除车辆历史数据列表(下载中心回调)",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "04506d2e7bc4f8509fabde75ac7ee475",
            "type": 3,
            "url": "/inner/api/vehicle/queryHistoryVehicleList",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "Wz3jjaxX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "Wz3jjaxX",
            "label": "获取轨迹点事件分页列表",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "9609dbb5e12bc80039bcdb81d08df968",
            "type": 3,
            "url": "/2b/v1.0/vehicleTrack/trackEventPage",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "d8xVVYlz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "d8xVVYlz",
            "label": "历史放电记录",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/2b/v1/pt/assetOperation/getDischargeHistoryPage",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "aXYwwWk2",
            "docType": 0,
            "httpMethod": "POST",
            "id": "aXYwwWk2",
            "label": "电池位置查询导出查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/inner/api/assetOperation/queryExportBatteryLocation",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "BXgRRmL8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "BXgRRmL8",
            "label": "查询barcode累计使用电量",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "175d748563cde6fd8e36ceeb813d27b2",
            "type": 3,
            "url": "/open/api/getUseElectricityPage",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "q2REeKNz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "q2REeKNz",
            "label": "车辆月使用情况分页查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "01ec51156fe07f6f6049afbde480f911",
            "type": 3,
            "url": "/2b/v1/pt/settlement/vehicleMonthlyUseQuery",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "Q2V0Ld4X",
            "docType": 0,
            "httpMethod": "POST",
            "id": "Q2V0Ld4X",
            "label": "车辆月使用情况详情分页查询（下载中心回调）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "c1c1c6494242770d3df29e9dcae3b400",
            "type": 3,
            "url": "/inner/api/settlement/queryVehicleMonthlyDetailUseList",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "E8rdMDNz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "E8rdMDNz",
            "label": "车辆行驶明细导出",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "de5221eb512fa37fc2d414735bb9fcbb",
            "type": 3,
            "url": "/2b/v1/pt/vehicleOperation/exportVehicleDrive",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "Q2V0MElX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "Q2V0MElX",
            "label": "车辆日使用情况分页查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "01ec51156fe07f6f6049afbde480f911",
            "type": 3,
            "url": "/open/api/v1/pt/settlement/vehicleDayUsagePageQuery",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "a26KeWN8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "a26KeWN8",
            "label": "更新租户/运营商权限（2B专用）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "ef776f94967632929c7794611a2758bb",
            "type": 3,
            "url": "/2b/v1.0/bims/permission/update",
            "version": ""
        },
        {
            "apiCount": 7,
            "deprecated": "",
            "docId": "7zLyn1j2",
            "docType": 0,
            "httpMethod": "",
            "id": "16aa0ca91781318f09ca578a7e38d875",
            "label": "持有方托管运营车辆",
            "origin": "",
            "parentId": "1537056406388080640",
            "type": 2,
            "url": "",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "32Qx6kBz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "32Qx6kBz",
            "label": "解除车辆（租户\\运营商）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "1370edc4f1e37a5850a842605eea13a6",
            "type": 3,
            "url": "/2b/v1.0/operationVehicle/importUnboundCarrier",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "32QMxdE2",
            "docType": 0,
            "httpMethod": "POST",
            "id": "32QMxdE2",
            "label": "获取资产持有方列表",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "16aa0ca91781318f09ca578a7e38d875",
            "type": 3,
            "url": "/2m/v1.0/hostingVehicle/merchantList",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "E8rddNDz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "E8rddNDz",
            "label": "校验电池是否已分配运营商",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "16d4f9354f75ab0a19131624e0739750",
            "type": 3,
            "url": "/2b/v1.0/pt/hostingBattery/checkOperator",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "q2REEYJz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "q2REEYJz",
            "label": "历史放电记录导出",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/2b/v1/pt/assetOperation/exportDischargeHistory",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "Q2V004NX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "Q2V004NX",
            "label": "累计使用电量导出查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/inner/api/assetOperation/queryExportUseElectricity",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "B2lGGDVz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "B2lGGDVz",
            "label": "查询barcode历史充电记录",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "175d748563cde6fd8e36ceeb813d27b2",
            "type": 3,
            "url": "/open/api/getChargeHistoryPage",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "nzDORknX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "nzDORknX",
            "label": "车辆月使用情况分页查询导出（下载中心）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "01ec51156fe07f6f6049afbde480f911",
            "type": 3,
            "url": "/2b/v1/pt/settlement/exportVehicleMonthlyUseQuery",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "kXOg0M7X",
            "docType": 0,
            "httpMethod": "POST",
            "id": "kXOg0M7X",
            "label": "车辆日使用情况分页查询（下载中心回调）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "c1c1c6494242770d3df29e9dcae3b400",
            "type": 3,
            "url": "/inner/api/settlement/queryVehicleDayUsageList",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "qXb7mevz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "qXb7mevz",
            "label": "车辆充电明细导出",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "de5221eb512fa37fc2d414735bb9fcbb",
            "type": 3,
            "url": "/2b/v1/pt/vehicleOperation/exportVehicleCharge",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "kXOg67lX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "kXOg67lX",
            "label": "电池月电量查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "01ec51156fe07f6f6049afbde480f911",
            "type": 3,
            "url": "/open/api/v1/pt/settlement/batMonthlyDisceQuery",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "P81OGGKz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "P81OGGKz",
            "label": "查询运营商已授权权限树（2B专用）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "ef776f94967632929c7794611a2758bb",
            "type": 3,
            "url": "/2b/v1.0/bims/permission/grantedTree",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "W2oAeM9X",
            "docType": 0,
            "httpMethod": "POST",
            "id": "W2oAeM9X",
            "label": "获取运营商列表",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "1370edc4f1e37a5850a842605eea13a6",
            "type": 3,
            "url": "/2b/v1.0/operationVehicle/carrierList",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "qXb77MEz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "qXb77MEz",
            "label": "快速出库",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "16d4f9354f75ab0a19131624e0739750",
            "type": 3,
            "url": "/2b/v1.0/pt/hostingBattery/quickOutbound",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "pX9ggNA2",
            "docType": 0,
            "httpMethod": "POST",
            "id": "pX9ggNA2",
            "label": "运营车辆管理-导出",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "16aa0ca91781318f09ca578a7e38d875",
            "type": 3,
            "url": "/2m/v1.0/hostingVehicle/export",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "nzDOOYaX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "nzDOOYaX",
            "label": "电池位置查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/2b/v1/pt/assetOperation/getBatteryLocationPage",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "kXOggYxX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "kXOggYxX",
            "label": "电池真实SOC导出查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/inner/api/assetOperation/queryExportActualSoc",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "aXYwwBk2",
            "docType": 0,
            "httpMethod": "POST",
            "id": "aXYwwBk2",
            "label": "查询barcode历史放电记录",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "175d748563cde6fd8e36ceeb813d27b2",
            "type": 3,
            "url": "/open/api/getDischargeHistoryPage",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "K8MgNWjz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "K8MgNWjz",
            "label": "车辆月使用情况详情分页查询导出（下载中心）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "01ec51156fe07f6f6049afbde480f911",
            "type": 3,
            "url": "/2b/v1/pt/settlement/exportVehicleMonthlyDetailUseQuery",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "a85aK0R8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "a85aK0R8",
            "label": "电池月电量分页查询（下载中心回调）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "c1c1c6494242770d3df29e9dcae3b400",
            "type": 3,
            "url": "/inner/api/settlement/queryBatMonthlyDisceList",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "a85apjO8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "a85apjO8",
            "label": "电池日电量分页查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "01ec51156fe07f6f6049afbde480f911",
            "type": 3,
            "url": "/open/api/v1/pt/settlement/batDailyDiscePageQuery",
            "version": ""
        },
        {
            "apiCount": 10,
            "deprecated": "",
            "docId": "e24kqMjz",
            "docType": 0,
            "httpMethod": "",
            "id": "1370edc4f1e37a5850a842605eea13a6",
            "label": "运营车辆清单",
            "origin": "",
            "parentId": "1537056406388080640",
            "type": 2,
            "url": "",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "K2Zj9bl2",
            "docType": 0,
            "httpMethod": "POST",
            "id": "K2Zj9bl2",
            "label": "解除车辆历史记录列表",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "16aa0ca91781318f09ca578a7e38d875",
            "type": 3,
            "url": "/2m/v1.0/hostingVehicle/historyPage",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "7zLO7VlX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "7zLO7VlX",
            "label": "分页查询运营商（商户下部门）（2B专用）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "ef776f94967632929c7794611a2758bb",
            "type": 3,
            "url": "/2b/v1.0/bims/merchant/dept/page",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "L2kJJejz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "L2kJJejz",
            "label": "校验电池是否可出库",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "16d4f9354f75ab0a19131624e0739750",
            "type": 3,
            "url": "/2b/v1.0/pt/hostingBattery/checkOutbound",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "K8MggYwz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "K8MggYwz",
            "label": "电池位置查询导出",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/2b/v1/pt/assetOperation/exportBatteryLocation",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "a85aaYQ8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "a85aaYQ8",
            "label": "月用电量查询导出查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/inner/api/assetOperation/queryExportMonthUse",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "W2oA0MrX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "W2oA0MrX",
            "label": "车辆日使用情况分页查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "01ec51156fe07f6f6049afbde480f911",
            "type": 3,
            "url": "/2b/v1/pt/settlement/vehicleDayUsagePageQuery",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "xXaZjw1z",
            "docType": 0,
            "httpMethod": "POST",
            "id": "xXaZjw1z",
            "label": "电池日电量分页查询（下载中心回调）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "c1c1c6494242770d3df29e9dcae3b400",
            "type": 3,
            "url": "/inner/api/settlement/queryBatDailyDisceList",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "P81KD0dz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "P81KD0dz",
            "label": "查询所有车牌（过滤租户\\运营商）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "1370edc4f1e37a5850a842605eea13a6",
            "type": 3,
            "url": "/2b/v1.0/operationVehicle/vehiclePlateList",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "nzDO90wX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "nzDO90wX",
            "label": "电池换电时刻电量查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "175d748563cde6fd8e36ceeb813d27b2",
            "type": 3,
            "url": "/open/api/getSwapTimeSoc",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "pX9g1pj2",
            "docType": 0,
            "httpMethod": "POST",
            "id": "pX9g1pj2",
            "label": "是否租户",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "1370edc4f1e37a5850a842605eea13a6",
            "type": 3,
            "url": "/2b/v1.0/operationVehicle/isTenant",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "JzA339y8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "JzA339y8",
            "label": "获取运营商列表",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "16d4f9354f75ab0a19131624e0739750",
            "type": 3,
            "url": "/2b/v1.0/pt/hostingBattery/getMerchantDeptList",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "7zLOOPjX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "7zLOOPjX",
            "label": "运营车辆管理-解除车辆历史记录-导出",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "16aa0ca91781318f09ca578a7e38d875",
            "type": 3,
            "url": "/2m/v1.0/hostingVehicle/exportHistory",
            "version": ""
        },
        {
            "apiCount": 16,
            "deprecated": "",
            "docId": "58ppp5L8",
            "docType": 0,
            "httpMethod": "",
            "id": "01ec51156fe07f6f6049afbde480f911",
            "label": "结算中心",
            "origin": "",
            "parentId": "1537056406388080640",
            "type": 2,
            "url": "",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "W2oAAoPX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "W2oAAoPX",
            "label": "累计使用电量",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/2b/v1/pt/assetOperation/getUseElectricityPage",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "Q2V00ENX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "Q2V00ENX",
            "label": "查询车辆累计使用里程",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "175d748563cde6fd8e36ceeb813d27b2",
            "type": 3,
            "url": "/open/api/vehicleMileagePageQuery",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "K2ZwOQx8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "K2ZwOQx8",
            "label": "车辆日使用情况分页查询（下载中心）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "01ec51156fe07f6f6049afbde480f911",
            "type": 3,
            "url": "/2b/v1/pt/settlement/exportVehicleDayUsagePageQuery",
            "version": ""
        },
        {
            "apiCount": 2,
            "deprecated": "",
            "docId": "7zLOyZoX",
            "docType": 0,
            "httpMethod": "",
            "id": "6a38115bfa7cfdd45026141a42c4649b",
            "label": "excel模板下载",
            "origin": "",
            "parentId": "1537056406388080640",
            "type": 2,
            "url": "",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "wXnkk6Gz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "wXnkk6Gz",
            "label": "运营车辆清单-导出",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "1370edc4f1e37a5850a842605eea13a6",
            "type": 3,
            "url": "/2b/v1.0/operationVehicle/export",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "K2ZwwB08",
            "docType": 0,
            "httpMethod": "POST",
            "id": "K2ZwwB08",
            "label": "累计使用电量导出",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/2b/v1/pt/assetOperation/exportUseElectricity",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "bXKZknN8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "bXKZknN8",
            "label": "电池月电量查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "01ec51156fe07f6f6049afbde480f911",
            "type": 3,
            "url": "/2b/v1/pt/settlement/batMonthlyDisceQuery",
            "version": ""
        },
        {
            "apiCount": 6,
            "deprecated": "",
            "docId": "K2Zj9pv2",
            "docType": 0,
            "httpMethod": "",
            "id": "ef776f94967632929c7794611a2758bb",
            "label": "BIMS 权限管理 Controller",
            "origin": "",
            "parentId": "1537056406388080640",
            "type": 2,
            "url": "",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "qXB640bX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "qXB640bX",
            "label": "解除车辆历史记录列表",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "1370edc4f1e37a5850a842605eea13a6",
            "type": 3,
            "url": "/2b/v1.0/operationVehicle/historyPage",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "bXKZZyl8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "bXKZZyl8",
            "label": "电池真实SOC",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/2b/v1/pt/assetOperation/getActualSocPage",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "ez7VP49X",
            "docType": 0,
            "httpMethod": "POST",
            "id": "ez7VP49X",
            "label": "电池月电量查询导出（下载中心）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "01ec51156fe07f6f6049afbde480f911",
            "type": 3,
            "url": "/2b/v1/pt/settlement/exportBatMonthlyDisceQuery",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "q2REEJxz",
            "docType": 0,
            "httpMethod": "POST",
            "id": "q2REEJxz",
            "label": "解除历史数据-导出",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "1370edc4f1e37a5850a842605eea13a6",
            "type": 3,
            "url": "/2b/v1.0/operationVehicle/exportHistory",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "ez7VVYeX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "ez7VVYeX",
            "label": "电池真实SOC导出",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/2b/v1/pt/assetOperation/exportActualSoc",
            "version": ""
        },
        {
            "apiCount": 6,
            "deprecated": "",
            "docId": "VXELLEv8",
            "docType": 0,
            "httpMethod": "",
            "id": "de5221eb512fa37fc2d414735bb9fcbb",
            "label": "车辆运营分析",
            "origin": "",
            "parentId": "1537056406388080640",
            "type": 2,
            "url": "",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "NzvQB6LX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "NzvQB6LX",
            "label": "电池日电量分页查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "01ec51156fe07f6f6049afbde480f911",
            "type": 3,
            "url": "/2b/v1/pt/settlement/batDailyDiscePageQuery",
            "version": ""
        },
        {
            "apiCount": 7,
            "deprecated": "",
            "docId": "V2JRR7Y2",
            "docType": 0,
            "httpMethod": "",
            "id": "175d748563cde6fd8e36ceeb813d27b2",
            "label": "运营监控数据",
            "origin": "",
            "parentId": "1537056406388080640",
            "type": 2,
            "url": "",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "NzvQQgqX",
            "docType": 0,
            "httpMethod": "POST",
            "id": "NzvQQgqX",
            "label": "月用电量查询",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/2b/v1/pt/assetOperation/getMonthUsePage",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "a26o9dW8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "a26o9dW8",
            "label": "电池日电量查询导出（下载中心）",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "01ec51156fe07f6f6049afbde480f911",
            "type": 3,
            "url": "/2b/v1/pt/settlement/exportBatDailyDiscePageQuery",
            "version": ""
        },
        {
            "apiCount": 1,
            "deprecated": "",
            "docId": "32QMMoE2",
            "docType": 0,
            "httpMethod": "",
            "id": "66436718f202af900d43aae3b49e6798",
            "label": "电池出库历史-下载中心回调接口",
            "origin": "",
            "parentId": "1537056406388080640",
            "type": 2,
            "url": "",
            "version": ""
        },
        {
            "apiCount": 0,
            "deprecated": "$false$",
            "docId": "a26ooYl8",
            "docType": 0,
            "httpMethod": "POST",
            "id": "a26ooYl8",
            "label": "月用电量查询导出",
            "origin": "/battery-investor-service/battery-investor-service",
            "parentId": "7f298dced62f86c0f2469c2a8e273d8f",
            "type": 3,
            "url": "/2b/v1/pt/assetOperation/exportMonthUse",
            "version": ""
        },
        {
            "apiCount": 6,
            "deprecated": "",
            "docId": "BXgRv3Z8",
            "docType": 0,
            "httpMethod": "",
            "id": "c1c1c6494242770d3df29e9dcae3b400",
            "label": "结算中心 - 下载中心回调接口",
            "origin": "",
            "parentId": "1537056406388080640",
            "type": 2,
            "url": "",
            "version": ""
        },
        {
            "apiCount": 1,
            "deprecated": "",
            "docId": "32Qx6bWz",
            "docType": 0,
            "httpMethod": "",
            "id": "86e15f50f37251b0155b9e621a7438d5",
            "label": "HealthController",
            "origin": "",
            "parentId": "1537056406388080640",
            "type": 2,
            "url": "",
            "version": ""
        },
        {
            "apiCount": 7,
            "deprecated": "",
            "docId": "P81OGAez",
            "docType": 0,
            "httpMethod": "",
            "id": "16d4f9354f75ab0a19131624e0739750",
            "label": "在管电池清单 Controller",
            "origin": "",
            "parentId": "1537056406388080640",
            "type": 2,
            "url": "",
            "version": ""
        },
        {
            "apiCount": 1,
            "deprecated": "",
            "docId": "VzNZMg9z",
            "docType": 0,
            "httpMethod": "",
            "id": "026d537c99c22307070824ea569f3034",
            "label": "认证权限controller",
            "origin": "",
            "parentId": "1537056406388080640",
            "type": 2,
            "url": "",
            "version": ""
        },
        {
            "apiCount": 3,
            "deprecated": "",
            "docId": "m8wooBK8",
            "docType": 0,
            "httpMethod": "",
            "id": "04506d2e7bc4f8509fabde75ac7ee475",
            "label": "OpenApiHostingVehicleController",
            "origin": "",
            "parentId": "1537056406388080640",
            "type": 2,
            "url": "",
            "version": ""
        }
    ],
    "msg": ""
}
   */